name: clue_get
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  flutter_spinkit: ^5.1.0
  flutter_screenutil: ^5.5.3+2
  provider: ^6.0.3
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.9
  get: ^4.6.5
  http: ^0.13.4
  textfield_tags: ^2.0.0+1
  like_button: ^2.0.4
  simple_tags: ^0.0.4
  flutter_slidable: ^2.0.0
  textfield_datepicker: ^0.1.0

  cloud_firestore: ^3.1.18
  firebase_core: ^1.10.2
  firebase_database: ^9.0.16
  firebase_helpers: ^0.5.0
  firebase_auth: ^3.3.20
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/image/
    - assets/json/check.json
    - assets/json/country.json
  fonts:
    - family: Poppins-R
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins-B
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Poppins-M
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins-S
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: Roboto-B
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Roboto-M
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: Roboto-R
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf